### ISSUE TITLE
vite3.0, npm run build-storybook error.

### ISSUE THREAD

**Issue by limbyungki** [mikinovation/storybook-addon-vuetify3#21]
info @storybook/vue3 v6.5.9
info
info => Cleaning outputDir: C:\workspace\seegene-lis-frontend\storybook-static
info => Loading presets
info => Compiling manager..
vite v3.0.0 building for production...
transforming (102) node_modules\@storybook\store\dist\esm\hooks.jsERR! => Failed to build the manager
ERR! Module not found: Error: Can't resolve 'vuetify/directives' in 'C:\workspace\seegene-lis-frontend\node_modules\storybook-addon-vuetify3\dist\decorators'
ERR! TypeError: previewBuilder.bail is not a function
ERR!     at C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:219:26
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:218:28)
ERR!     at async buildStatic (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:254:5)
ERR!  TypeError: previewBuilder.bail is not a function
ERR!     at C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:219:26
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:218:28)
ERR!     at async buildStatic (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:254:5)
info => Loading presets
transforming (117) node_modules\@storybook\vue3\dist\esm\client\index.js

**Comment by CiaranPearse** [comment]
Also getting similar issue. Small snippet below - It will works but there are at least 60 errors like the ones below

`ERROR in ./node_modules/vuetify/lib/util/defineComponent.mjs 38:6-17
Can't import the named export 'watchEffect' from non EcmaScript module (only default export is available)
 @ ./node_modules/vuetify/lib/util/index.mjs
 @ ./node_modules/vuetify/lib/framework.mjs
 @ ./node_modules/storybook-addon-vuetify3/dist/decorators/withVuetify.js
 @ ./node_modules/storybook-addon-vuetify3/dist/decorators/index.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/manager/index.js ./node_modules/@storybook/addon-links/manager.js ./node_modules/@storybook/addon-docs/manager.js ./node_modules/@storybook/addon-controls/manager.js ./node_modules/@storybook/addon-actions/manager.js ./node_modules/@storybook/addon-backgrounds/manager.js ./node_modules/@storybook/addon-viewport/manager.js ./node_modules/@storybook/addon-toolbars/manager.js ./node_modules/@storybook/addon-measure/manager.js ./node_modules/@storybook/addon-outline/manager.js ./node_modules/@storybook/addon-interactions/manager.js ./node_modules/storybook-addon-vuetify3/dist/decorators/index.js

ERROR in ./node_modules/storybook-addon-vuetify3/dist/decorators/withVuetify.js
Module not found: Error: Can't resolve 'vuetify/components' in 'C:\Users\foleycix\codebase\iVite\node_modules\storybook-addon-vuetify3\dist\decorators'
 @ ./node_modules/storybook-addon-vuetify3/dist/decorators/withVuetify.js 18:41-70
 @ ./node_modules/storybook-addon-vuetify3/dist/decorators/index.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/manager/index.js ./node_modules/@storybook/addon-links/manager.js ./node_modules/@storybook/addon-docs/manager.js ./node_modules/@storybook/addon-controls/manager.js ./node_modules/@storybook/addon-actions/manager.js ./node_modules/@storybook/addon-backgrounds/manager.js ./node_modules/@storybook/addon-viewport/manager.js ./node_modules/@storybook/addon-toolbars/manager.js ./node_modules/@storybook/addon-measure/manager.js ./node_modules/@storybook/addon-outline/manager.js ./node_modules/@storybook/addon-interactions/manager.js ./node_modules/storybook-addon-vuetify3/dist/decorators/index.js`
