### ISSUE TITLE
Storybook build error.

### ISSUE THREAD

**Issue by limbyungki** [mikinovation/storybook-addon-vuetify3#28]
npm run build-storybook
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> seegene-lis-frontend@0.0.5 build-storybook
> build-storybook

info @storybook/vue3 v6.5.10
info
info => Cleaning outputDir: C:\workspace\seegene-lis-frontend\storybook-static
info => Loading presets
info => Compiling manager..
ERR! => Failed to build the manager
ERR! Module not found: Error: Can't resolve 'vuetify/directives' in 'C:\workspace\seegene-lis-frontend\node_modules\storybook-addon-vuetify3\dist\decorators'       
ERR! TypeError: previewBuilder.bail is not a function
ERR!     at C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:219:26
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:218:28)
ERR!     at async buildStatic (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:254:5)
ERR!  TypeError: previewBuilder.bail is not a function
ERR!     at C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:219:26
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Promise.all (index 0)
ERR!     at async buildStaticStandalone (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:218:28)
ERR!     at async buildStatic (C:\workspace\seegene-lis-frontend\node_modules\@storybook\core-server\dist\cjs\build-static.js:254:5)
info => Loading presets
vite v3.0.9 building for production...

---------------------------------------
<preview.js>
import { withVuetify } from 'storybook-addon-vuetify3/dist/decorators';
import { app } from '@storybook/vue3';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    expanded: true,
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

export const decorators = [
  withVuetify,
  (_) => {
    // loadFonts();

----------------------------

<plugins/vuetify.js>

import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';

// Vuetify
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';

export default createVuetify({
  components,
  directives,
});

**Comment by limbyungki** [comment]
"storybook-addon-vuetify3": "^2.0.5",
 "@storybook/builder-vite": "^0.2.2",

**Comment by cxl-todd** [comment]
I am also receiving this error with the default builder.
